version: '3'


services:

# Python
  py:
    build: 
      context: .
      dockerfile: python_image/Dockerfile

    image: mlflow_py_demo

    ports:
      - "8888:8888"

    volumes:
      - "${MLFLOW_DEMO_DIRECTORY:-/tmp}:/opt/project"
      - "${MLFLOW_TRACKING_DIRECTORY:-/tmp}/artifacts:/artifacts"

    # command to start jupyter notebook server
    command: >
       jupyter notebook --no-browser --ip 0.0.0.0 
          --allow-root --password='' --NotebookApp.token=''
          --notebook-dir=/opt/project

# R
  r:
    build: 
      context: .
      dockerfile: mlflow_r_image/Dockerfile

    image: mlflow_r_demo

    
    ports:
      - "8787:8787"

    environment:
      DISABLE_AUTH:  'true'

    volumes:
      - "${MLFLOW_DEMO_DIRECTORY:-/tmp}:/home/rstudio/project"
      - "${MLFLOW_TRACKING_DIRECTORY:-/tmp}/artifacts:/artifacts"


# mlflow_tracker - file store
  file_tracker:
    build: 
      context: .
      dockerfile: mlflow_server/Dockerfile

    image: mlflow_server
    
    ports:
      - "5000:5000"

    volumes:
      - "${MLFLOW_TRACKING_DIRECTORY:-/tmp}/tracking:/tracking"
      - "${MLFLOW_TRACKING_DIRECTORY:-/tmp}/artifacts:/artifacts"

    command: >
      mlflow server
        --file-store /tracking
        --default-artifact-root /artifacts 
        --host 0.0.0.0
        --port 5000



# mlflow_tracker - database
  db_tracker:
    build:
      context: .
      dockerfile: mlflow_server/Dockerfile

    image: mlflow_server

    ports:
      - "5001:5001"

    volumes:
      - "${MLFLOW_TRACKING_DIRECTORY:-/tmp}/artifacts:/artifacts"

    command: >
      mlflow server
        --backend-store-uri postgresql://mlflow_user:mlflow_pw@pgdb/mlflow_db
        --default-artifact-root /artifacts
        --host 0.0.0.0
        --port 5001


  # postgres database
  pgdb:

    image: postgres:10

    ports:
      - "5432:5432"

    environment:
      POSTGRES_PASSWORD: mlflow_pw
      POSTGRES_USER: mlflow_user
      POSTGRES_DB: mlflow_db

    volumes:
      - "${MLFLOW_TRACKING_DIRECTORY:-/tmp}/postgres/data:/var/lib/postgresql/data"


  # postgres admin
  pgadmin:

    image: dpage/pgadmin4

    ports:
      - "80:80"

    environment:
      PGADMIN_DEFAULT_EMAIL: "mlflow@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: pgadmin4

    volumes:
      - "${MLFLOW_TRACKING_DIRECTORY:-/tmp}/postgres/pgadmin:/var/lib/pgadmin"

