version: '3'


services:

# Python
  py:
    build: 
      context: .
      dockerfile: python_image/Dockerfile

    image: mlflow_py_demo

    ports:
      - "8888:8888"

    volumes:
      - "${MLFLOW_DEMO_DIRECTORY:-/tmp}:/opt/project"
      - "${MLFLOW_TRACKING_DIRECTORY:-/tmp}/artifacts:/artifacts"

    # command to start jupyter notebook server
    command: >
       jupyter notebook --no-browser --ip 0.0.0.0 
          --allow-root --password='' --NotebookApp.token=''
          --notebook-dir=/opt/project

# R
  r:
    build: 
      context: .
      dockerfile: mlflow_r_image/Dockerfile

    image: mlflow_r_demo

    
    ports:
      - "8787:8787"

    environment:
      DISABLE_AUTH:  'true'

    volumes:
      - "${MLFLOW_DEMO_DIRECTORY:-/tmp}:/home/rstudio/project"
      - "${MLFLOW_TRACKING_DIRECTORY:-/tmp}/artifacts:/artifacts"


# mlflow_tracker
  tracking:
    build: 
      context: .
      dockerfile: mlflow_server/Dockerfile

    image: mlflow_server
    
    ports:
      - "5000:5000"

    volumes:
      - "${MLFLOW_TRACKING_DIRECTORY:-/tmp}/tracking:/tracking"
      - "${MLFLOW_TRACKING_DIRECTORY:-/tmp}/artifacts:/artifacts"

    command: >
      mlflow server 
        --file-store /tracking 
        --default-artifact-root /artifacts 
        --host 0.0.0.0


    